const citiesConstant = [
  { name: "Fayzabad", state: "Badakhshan" },
  { name: "Baharak", state: "Badakhshan" },
  { name: "Jurm", state: "Badakhshan" },
  { name: "Khash", state: "Badakhshan" },
  { name: "Ishkashim", state: "Badakhshan" },
  { name: "Shahr-e Bozorg", state: "Badakhshan" },
  { name: "Tagab", state: "Badakhshan" },
  { name: "Qala-e-Naw", state: "Badghis" },
  { name: "Ghormach", state: "Badghis" },
  { name: "Bala Murghab", state: "Badghis" },
  { name: "Jawand", state: "Badghis" },
  { name: "Murgab", state: "Badghis" },
  { name: "Ab Kamari", state: "Badghis" },
  { name: "Qalat", state: "Zabul" },
  { name: "Shinkay", state: "Zabul" },
  { name: "Mizan", state: "Zabul" },
  { name: "Atghar", state: "Zabul" },
  { name: "Arghandab", state: "Zabul" },
  { name: "Shahjoy", state: "Zabul" },
  { name: "Naw Bahar", state: "Zabul" },
  { name: "Central", state: "Central and Western" },
  { name: "Sheung Wan", state: "Central and Western" },
  { name: "Mid-levels", state: "Central and Western" },
  { name: "Kennedy Town", state: "Central and Western" },
  { name: "Sai Ying Pun", state: "Central and Western" },
  { name: "Tai Koo", state: "Eastern" },
  { name: "Quarry Bay", state: "Eastern" },
  { name: "Sai Wan Ho", state: "Eastern" },
  { name: "Shau Kei Wan", state: "Eastern" },
  { name: "Chai Wan", state: "Eastern" },
  { name: "Aberdeen", state: "Southern" },
  { name: "Repulse Bay", state: "Southern" },
  { name: "Stanley", state: "Southern" },
  { name: "Wong Chuk Hang", state: "Southern" },
  { name: "Deep Water Bay", state: "Southern" },
  { name: "Port Blair", state: "Andaman and Nicobar Islands" },
  { name: "Havelock Island", state: "Andaman and Nicobar Islands" },
  { name: "Neil Island", state: "Andaman and Nicobar Islands" },
  { name: "Mayabunder", state: "Andaman and Nicobar Islands" },
  { name: "Diglipur", state: "Andaman and Nicobar Islands" },
  { name: "Hyderabad", state: "Andhra Pradesh" },
  { name: "Visakhapatnam", state: "Andhra Pradesh" },
  { name: "Vijayawada", state: "Andhra Pradesh" },
  { name: "Guntur", state: "Andhra Pradesh" },
  { name: "Nellore", state: "Andhra Pradesh" },
  { name: "Kurnool", state: "Andhra Pradesh" },
  { name: "Itanagar", state: "Arunachal Pradesh" },
  { name: "Naharlagun", state: "Arunachal Pradesh" },
  { name: "Tawang", state: "Arunachal Pradesh" },
  { name: "Bomdila", state: "Arunachal Pradesh" },
  { name: "Pasighat", state: "Arunachal Pradesh" },
  { name: "Aalo (Along)", state: "Arunachal Pradesh" },
];
module.exports = { citiesConstant };
